#!/usr/bin/bash
read folderName
read fileName
mkdir $folderName
cd $folderName
touch $fileName
echo "Hello" >> exampleFile
for x in {1..20}
do
	if [ $(($x % 2)) -eq 0 ]; then
		echo $x >> $fileName
	fi 
done